### ISSUE TITLE
Memory leak in `num_threads::is_single_threaded()` on Apple platforms

### ISSUE THREAD

**Issue by aw-cf** [jhpratt/num-threads#16]
The implementation for `num_threads::is_single_threaded()` is leaking `thread_count` mach ports on every call.

This is because `thread_state` is ignored currently. The correct usage of this API requires calling `mach_port_deallocate` and  `vm_deallocate`. One example of using this API without leaking memory would be can be found [here](https://github.com/apple/swift/blob/c2716e4b2fd5105e45fe637508cd37c0f5e78eb0/stdlib/public/runtime/CrashHandlerMacOS.cpp#L178-L194).

This issue was introduced with #6 (https://github.com/jhpratt/num_threads/commit/b12a1c8cea0f5dbd4e83af41670c5dfaa3add0cf) and it could make sense to revert this change given fixing the current code would likely lead to more allocations/deallocations than the previous implementation.

**Comment by jhpratt** [comment]
I have no problem fixing a memory leak, but reverting #6 is not an option given that it would require going back to using non-public APIs.

**Comment by thibault-ml** [comment]
Fixing forward is definitely fine. It should be easy to fix. `mach_port_deallocate` needs to be called for each `thread_state[x]`, and then `vm_deallocate` called on `thread_state` with `thread_count * sizeof(mach_port_t)`

Also, I believe we shouldn't need to manually declare the interface of `task_threads` or `task_inspect_t`, since they are already defined in Rust's libc:
https://github.com/rust-lang/libc/blob/main/src/unix/bsd/apple/mod.rs#L6136-L6140

**Comment by thibault-ml** [comment]
@jhpratt We've got a working fix, we'll put up a PR today.

**Comment by aw-cf** [comment]
> I have no problem fixing a memory leak, but reverting #6 is not an option given that it would require going back to using non-public APIs.

That's a valid point indeed

**Comment by complexspaces** [comment]
Its a bit late but sorry to everyone for introducing the memory leak originally 😅. I was a lot newer at lower-level macOS principles at the time. Thanks for fixing it up after the fact.

**Comment by jhpratt** [comment]
@complexspaces mistakes happen! It's not a big deal and was released just two weeks after it was first reported.
